### ISSUE TITLE
Linux运行问题

### ISSUE THREAD

**Issue by Danfi** [langmansh/AKStreamWebUI#16]
代码里表名大小写不统一，linux下mysql会区分大小写，会导致运行错误

**Comment by langmansh** [comment]
在mysql配置里面直接忽略大小写


------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Saturday, May 29, 2021 2:51 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[langmansh/AKStreamWebUI] Linux运行问题 (#16)





 
代码里表名大小写不统一，linux下mysql会区分大小写，会导致运行错误
