### ISSUE TITLE
设备预览

### ISSUE THREAD

**Issue by lt-zq** [langmansh/AKStreamWebUI#17]
添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by langmansh** [comment]
推流端口是随机的还是固定？




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Jun 1, 2021 5:56 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)





 
添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by lt-zq** [comment]
每次请求获取的MainId都是固定的&nbsp; 请问这个是在哪设置的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 上午8:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 推流端口是随机的还是固定？ 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Send time:&amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM 
 ***@***.***&amp;gt;;  
 ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
   
 添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by langmansh** [comment]
MainId是第一次启动服务的时候，会自动去获取设备添加到数据库的，MainId在自动添加设备的时候会自动填写的




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Wednesday, Jun 2, 2021 9:04 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 每次请求获取的MainId都是固定的&amp;nbsp; 请问这个是在哪设置的呢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月2日(星期三) 上午8:57 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
  推流端口是随机的还是固定？  
   
   
   
   
  ------------------&amp;amp;nbsp;Original&amp;amp;nbsp;------------------  
  From: ***@***.***&amp;amp;gt;;  
  Send time:&amp;amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM  
  ***@***.***&amp;amp;gt;;   
  ***@***.***&amp;amp;gt;;   
  Subject: &amp;amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)  
   
   
   
   
   
     
  添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by lt-zq** [comment]
对，可是我手动添加设备(VideoChannels新增一条数据)后，预览返回给我的还是自动添加的那个MainId，导致我的画面还是同一个，是MediaServer只启动一个原因么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 上午9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 MainId是第一次启动服务的时候，会自动去获取设备添加到数据库的，MainId在自动添加设备的时候会自动填写的 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Send time:&amp;nbsp;Wednesday, Jun 2, 2021 9:04 AM 
 ***@***.***&amp;gt;;  
 ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
  每次请求获取的MainId都是固定的&amp;amp;nbsp; 请问这个是在哪设置的呢  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月2日(星期三) 上午8:57  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)  
   
   
   
   
   
   推流端口是随机的还是固定？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;Original&amp;amp;amp;nbsp;------------------   
   From: ***@***.***&amp;amp;amp;gt;;   
   Send time:&amp;amp;amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM   
   ***@***.***&amp;amp;amp;gt;;    
   ***@***.***&amp;amp;amp;gt;;    
   Subject: &amp;amp;amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)   
     
     
     
     
     
       
   添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by langmansh** [comment]
手动添加设备的话，不能添加已有的相同设备，比如channel id和sipdeviceid是一样的




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Wednesday, Jun 2, 2021 9:10 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 对，可是我手动添加设备(VideoChannels新增一条数据)后，预览返回给我的还是自动添加的那个MainId，导致我的画面还是同一个，是MediaServer只启动一个原因么 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月2日(星期三) 上午9:05 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
  MainId是第一次启动服务的时候，会自动去获取设备添加到数据库的，MainId在自动添加设备的时候会自动填写的  
   
   
   
   
  ------------------&amp;amp;nbsp;Original&amp;amp;nbsp;------------------  
  From: ***@***.***&amp;amp;gt;;  
  Send time:&amp;amp;nbsp;Wednesday, Jun 2, 2021 9:04 AM  
  ***@***.***&amp;amp;gt;;   
  ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  Subject: &amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)  
   
   
   
   
   
   每次请求获取的MainId都是固定的&amp;amp;amp;nbsp; 请问这个是在哪设置的呢   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年6月2日(星期三) 上午8:57   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)   
     
     
     
     
     
    推流端口是随机的还是固定？    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;nbsp;------------------    
    From: ***@***.***&amp;amp;amp;amp;gt;;    
    Send time:&amp;amp;amp;amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM    
    ***@***.***&amp;amp;amp;amp;gt;;     
    ***@***.***&amp;amp;amp;amp;gt;;     
    Subject: &amp;amp;amp;amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)    
       
       
       
       
       
         
    添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by lt-zq** [comment]
明白了 我在试一下 谢谢大神，我在问下 你刚说“推流端口是随机的还是固定”是什么意思呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 上午9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 手动添加设备的话，不能添加已有的相同设备，比如channel id和sipdeviceid是一样的 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Send time:&amp;nbsp;Wednesday, Jun 2, 2021 9:10 AM 
 ***@***.***&amp;gt;;  
 ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
  对，可是我手动添加设备(VideoChannels新增一条数据)后，预览返回给我的还是自动添加的那个MainId，导致我的画面还是同一个，是MediaServer只启动一个原因么  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月2日(星期三) 上午9:05  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)  
   
   
   
   
   
   MainId是第一次启动服务的时候，会自动去获取设备添加到数据库的，MainId在自动添加设备的时候会自动填写的   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;Original&amp;amp;amp;nbsp;------------------   
   From: ***@***.***&amp;amp;amp;gt;;   
   Send time:&amp;amp;amp;nbsp;Wednesday, Jun 2, 2021 9:04 AM   
   ***@***.***&amp;amp;amp;gt;;    
   ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   Subject: &amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)   
     
     
     
     
     
    每次请求获取的MainId都是固定的&amp;amp;amp;amp;nbsp; 请问这个是在哪设置的呢    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年6月2日(星期三) 上午8:57    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)    
       
       
       
       
       
     推流端口是随机的还是固定？     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;amp;nbsp;------------------     
     From: ***@***.***&amp;amp;amp;amp;amp;gt;;     
     Send time:&amp;amp;amp;amp;amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM     
     ***@***.***&amp;amp;amp;amp;amp;gt;;      
     ***@***.***&amp;amp;amp;amp;amp;gt;;      
     Subject: &amp;amp;amp;amp;amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)     
         
         
         
         
         
           
     添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by langmansh** [comment]
随机端口就是每次推流会随机打开已个端口，固定端口就是所有设备都会往一个端口上推




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Wednesday, Jun 2, 2021 9:15 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 明白了 我在试一下 谢谢大神，我在问下 你刚说“推流端口是随机的还是固定”是什么意思呢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年6月2日(星期三) 上午9:11 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
  手动添加设备的话，不能添加已有的相同设备，比如channel id和sipdeviceid是一样的  
   
   
   
   
  ------------------&amp;amp;nbsp;Original&amp;amp;nbsp;------------------  
  From: ***@***.***&amp;amp;gt;;  
  Send time:&amp;amp;nbsp;Wednesday, Jun 2, 2021 9:10 AM  
  ***@***.***&amp;amp;gt;;   
  ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  Subject: &amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)  
   
   
   
   
   
   对，可是我手动添加设备(VideoChannels新增一条数据)后，预览返回给我的还是自动添加的那个MainId，导致我的画面还是同一个，是MediaServer只启动一个原因么   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年6月2日(星期三) 上午9:05   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)   
     
     
     
     
     
    MainId是第一次启动服务的时候，会自动去获取设备添加到数据库的，MainId在自动添加设备的时候会自动填写的    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;nbsp;------------------    
    From: ***@***.***&amp;amp;amp;amp;gt;;    
    Send time:&amp;amp;amp;amp;nbsp;Wednesday, Jun 2, 2021 9:04 AM    
    ***@***.***&amp;amp;amp;amp;gt;;     
    ***@***.***&amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;gt;;     
    Subject: &amp;amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)    
       
       
       
       
       
     每次请求获取的MainId都是固定的&amp;amp;amp;amp;amp;nbsp; 请问这个是在哪设置的呢     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年6月2日(星期三) 上午8:57     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)     
         
         
         
         
         
      推流端口是随机的还是固定？      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      From: ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      Send time:&amp;amp;amp;amp;amp;amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;       
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;       
      Subject: &amp;amp;amp;amp;amp;amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)      
           
           
           
           
           
             
      添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by lt-zq** [comment]
懂了 谢谢大神解惑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 上午9:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 随机端口就是每次推流会随机打开已个端口，固定端口就是所有设备都会往一个端口上推 
 
 
 
 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------ 
 From: ***@***.***&amp;gt;; 
 Send time:&amp;nbsp;Wednesday, Jun 2, 2021 9:15 AM 
 ***@***.***&amp;gt;;  
 ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 Subject: &amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17) 
 
 
 
 
 
  明白了 我在试一下 谢谢大神，我在问下 你刚说“推流端口是随机的还是固定”是什么意思呢  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年6月2日(星期三) 上午9:11  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)  
   
   
   
   
   
   手动添加设备的话，不能添加已有的相同设备，比如channel id和sipdeviceid是一样的   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;Original&amp;amp;amp;nbsp;------------------   
   From: ***@***.***&amp;amp;amp;gt;;   
   Send time:&amp;amp;amp;nbsp;Wednesday, Jun 2, 2021 9:10 AM   
   ***@***.***&amp;amp;amp;gt;;    
   ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   Subject: &amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)   
     
     
     
     
     
    对，可是我手动添加设备(VideoChannels新增一条数据)后，预览返回给我的还是自动添加的那个MainId，导致我的画面还是同一个，是MediaServer只启动一个原因么    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年6月2日(星期三) 上午9:05    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)    
       
       
       
       
       
     MainId是第一次启动服务的时候，会自动去获取设备添加到数据库的，MainId在自动添加设备的时候会自动填写的     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;amp;nbsp;------------------     
     From: ***@***.***&amp;amp;amp;amp;amp;gt;;     
     Send time:&amp;amp;amp;amp;amp;nbsp;Wednesday, Jun 2, 2021 9:04 AM     
     ***@***.***&amp;amp;amp;amp;amp;gt;;      
     ***@***.***&amp;amp;amp;amp;amp;gt;; ***@***.***&amp;amp;amp;amp;amp;gt;;      
     Subject: &amp;amp;amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)     
         
         
         
         
         
      每次请求获取的MainId都是固定的&amp;amp;amp;amp;amp;amp;nbsp; 请问这个是在哪设置的呢      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2021年6月2日(星期三) 上午8:57      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      ***@***.******@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)      
           
           
           
           
           
       推流端口是随机的还是固定？       
             
             
             
             
       ------------------&amp;amp;amp;amp;amp;amp;amp;nbsp;Original&amp;amp;amp;amp;amp;amp;amp;nbsp;------------------       
       From: ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;;       
       Send time:&amp;amp;amp;amp;amp;amp;amp;nbsp;Tuesday, Jun 1, 2021 5:56 PM       
       ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;;        
       ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;;        
       Subject: &amp;amp;amp;amp;amp;amp;amp;nbsp;[langmansh/AKStreamWebUI] 设备预览 (#17)       
             
             
             
             
             
               
       添加了多个设备后，使用同一个流媒体，不同的设备预览的是同一个画面，请问大神是哪里配置错了么？

**Comment by lt-zq** [comment]
问题已经解决了，再次感谢大神




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langmansh/AKStreamWebUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 上午9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langmansh/AKStreamWebUI] 设备预览 (#17)





 
Closed #17.
