### ISSUE TITLE
登錄問題

### ISSUE THREAD

**Issue by yfk2012** [langmansh/AKStreamWebUI#9]
帐号：admin 密码：123456
無法登錄 
不知道是帳號問題還是驗證碼問題
問題已解決 ( 自己犯蠢

**Comment by langmansh** [comment]
提示什么具体描述下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;yfk2012&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 晚上10:38
收件人:&nbsp;&quot;langmansh/AKStreamWebUI&quot;<AKStreamWebUI@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[langmansh/AKStreamWebUI] 登錄問題 (#9)
